"""empty message

Revision ID: d55a7efed8b3
Revises: 4614cd6cd481
Create Date: 2018-12-25 22:43:51.950520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55a7efed8b3'
down_revision = '4614cd6cd481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('mem_limit', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'time_limit')
    op.drop_column('data', 'mem_limit')
    # ### end Alembic commands ###
